return {
	diagnostics = {
		Error = "",
		Warning = "",
		Information = "",
		Debug = "",
		Trace = "",
		Question = "",
		Hint = "",
	},
	git = {
		Add = "",
		Modify = "",
		Staged = "",
		Remove = "",
		Ignore = "",
		Rename = "",
		Diff = "",
		Repo = "",
		Merge = "",
		Unmerged = "",
		PullRequest = "",
		Untracked = "",
	},
	fs = {
		dir = {
			Closed = "",
			Open = "",
			Empty = "",
			EmptyOpen = "",
			Symlink = "",
		},
		file = {
			Default = "",
			Symlink = "",
		},
	},
	ui = {
		Search = "",
		SelectionCarret = "",
	},
	code_context = {
		File = " ",
		Module = " ",
		Namespace = " ",
		Package = " ",
		Class = " ",
		Method = " ",
		Property = " ",
		Field = " ",
		Constructor = " ",
		Enum = "練",
		Interface = "練",
		Function = " ",
		Variable = " ",
		Constant = " ",
		String = " ",
		Number = " ",
		Boolean = "◩ ",
		Array = " ",
		Object = " ",
		Key = " ",
		Null = "ﳠ ",
		EnumMember = " ",
		Struct = " ",
		Event = " ",
		Operator = " ",
		TypeParameter = " ",
	},
}
